# 민감 정보 저장 - 깃허브에서 안전하게 암호화
# 로깅시 마스킹 처리
# 워크플로우 실행 중에만 접근 가능

# organization, repository, environment에서 설정 가능
# 우선순위: environment level >> Repository level >> Organization level

name: secret
on: push

jobs:
  get-secret:
    runs-on: ubuntu-latest
    steps:
      - name: get secrets
        run: echo ${{ secrets.level }} # 미리 정의된 secret LEVEL 가져옴